version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pip"
    directory: "/dev-agent/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
