pull_request_rules:
  - name: Automatic merge PR from dependabot on passing CI
    conditions:
      - "author = dependabot[bot]"
      - "check-success = danger/danger"
      - "check-success = Check spell"
      - "check-success = Lint Flutter"
      - "check-success = Build iOS dev app"
      - "check-success = Build Android dev app"
      - "approved-reviews-by = shotaIDE"
    actions:
      merge:
        method: squash
