name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: 5.2.0
  collection: 1.18.0
  cupertino_icons: 1.0.8
  faker: 2.1.0
  firebase_auth: 5.1.3
  firebase_core: 3.3.0
  firebase_remote_config: 5.0.4
  flame: 1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.4
  in_app_review: 2.0.9
  intl: 0.19.0
  package_info_plus: 8.0.1
  shared_preferences: 2.2.3

dev_dependencies:
  analyzer: 6.4.1
  build_runner: 2.4.12
  cider: 0.2.8
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.8.0
  mocktail: 1.0.4
  pedantic_mono: 1.26.0
  test: 1.25.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
