name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  # dependabotがFlutterバージョンを推定することができるように指定
  flutter: ">=3.19.6"

dependencies:
  cloud_firestore: 4.17.3
  collection: 1.18.0
  cupertino_icons: 1.0.8
  faker: 2.1.0
  firebase_auth: 4.19.5
  firebase_core: 2.31.0
  firebase_remote_config: 4.4.5
  flame: 1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.1
  in_app_review: 2.0.9
  intl: 0.18.1
  package_info_plus: 8.0.0
  shared_preferences: 2.2.3

dev_dependencies:
  analyzer: 6.4.1
  build_runner: 2.4.9
  cider: 0.2.7
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.8.0
  mocktail: 1.0.3
  pedantic_mono: 1.27.0
  test: 1.24.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
