name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.2.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flame: ^1.8.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  pedantic_mono: ^1.23.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
