name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  # dependabotがFlutterバージョンを推定することができるように指定
  flutter: ">=3.19.1"

dependencies:
  cloud_firestore:
  collection:
  cupertino_icons:
  faker:
  firebase_auth:
  firebase_core:
  firebase_remote_config:
  flame:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  in_app_review:
  intl:
  package_info_plus:
  shared_preferences:

dev_dependencies:
  build_runner:
  cider:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  mocktail:
  pedantic_mono:
  test:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
