name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  # dependabotがFlutterバージョンを推定することができるように指定
  flutter: ">=3.19.4"

dependencies:
  cloud_firestore: 4.15.9
  collection: 1.18.0
  cupertino_icons: 1.0.6
  faker: 2.1.0
  firebase_auth: 4.17.9
  firebase_core: 2.27.2
  firebase_remote_config: 4.3.19
  flame: 1.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.1
  in_app_review: 2.0.9
  intl: 0.18.1
  package_info_plus: 4.2.0
  shared_preferences: 2.2.2

dev_dependencies:
  build_runner: 2.4.8
  cider: 0.2.7
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  json_serializable: 6.7.1
  mocktail: 1.0.3
  pedantic_mono: 1.26.0
  test: 1.24.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
