name: live_bresto
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  colomney_lints:
    git:
      url: https://github.com/shotaIDE/ColomneyFlutterLints.git
      ref: main
  environment_config: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
