name: live_bresto
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.2.0
  collection: ^1.16.0
  flame: ^1.8.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.3.3
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
