name: live_bresto
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  flame: ^1.8.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  colomney_lints:
    git:
      url: https://github.com/shotaIDE/ColomneyFlutterLints.git
      ref: main
  environment_config: ^3.1.0
  freezed: ^2.3.5
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
