name: CI / Android

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-dev-app:
    name: Build dev app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Generate uncommited Flutter files
        uses: ./.github/actions/generate-uncommited-flutter-files
      - name: Build Android dev app
        run: flutter build appbundle --dart-define SERVER_ENV=dev
