name: CI / dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  push-back-diffs-if-needed:
    name: Push back diffs after resolving Flutter dependencies if needed
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dart')
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.RAINBEEK_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.RAINBEEK_WORKFLOW_APP_PRIVATE_KEY_PEM }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          # CI がプッシュバック後に再度トリガーされることを保証するため、
          # デフォルトのトークン `GITHUB_TOKEN` の代わりに GitHub App トークンを使用する
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - name: Setup Git
        uses: ./.github/actions/setup-git
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: ./ios
      # dependabot が `pubspec.yaml` にバージョン制約を書き込んでしまう問題の回避策。
      # そのままにすると、次回のバージョン更新が動作しなくなる。
      - name: Revert pubspec.yaml
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git checkout main
          git switch "$BRANCH_NAME"
          git checkout main pubspec.yaml
      - name: Install Flutter dependencies
        run: bundle exec fastlane install_flutter_dependencies
        working-directory: ./ios
      - name: Commit
        run: |
          git add pubspec.yaml pubspec.lock
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'build: pubspec.yaml と pubspec.lock を修復'
          fi
      - name: Push back if needed
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git push origin "$BRANCH_NAME"
