name: CI / PR

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    name: Check PR title
    permissions:
      contents: read
      issues: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # PRのブランチ上におけるコミット数が多い場合に、Dangerでマージベースが見つからない
          # エラーが発生することを防ぐために、全ての履歴をフェッチ
          fetch-depth: 0
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
      - name: Run danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
